/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/user/Account.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AssistantList: typeof import('./src/components/ai_chat/AssistantList.vue')['default']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    Changepassword: typeof import('./src/components/user/changepassword.vue')['default']
    ChangePassword: typeof import('./src/components/user/ChangePassword.vue')['default']
    ChatAside: typeof import('./src/components/ai_chat/ChatAside.vue')['default']
    ChatPanel: typeof import('./src/components/ai_chat/ChatPanel.vue')['default']
    ConversationTest: typeof import('./src/components/ai_test/ConversationTest.vue')['default']
    CreateAssistantModal: typeof import('./src/components/ai_chat/CreateAssistantModal.vue')['default']
    EditAssistantModal: typeof import('./src/components/ai_chat/EditAssistantModal.vue')['default']
    EditKnowledgeModal: typeof import('./src/components/ai_chat/EditKnowledgeModal.vue')['default']
    Knowledge: typeof import('./src/components/ai_test/Knowledge.vue')['default']
    KnowledgeHome: typeof import('./src/components/knowledge/KnowledgeHome.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    PrivacyPolicy: typeof import('./src/components/setting/PrivacyPolicy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingInput: typeof import('./src/components/ai_test/SettingInput.vue')['default']
    SystemSetting: typeof import('./src/components/setting/SystemSetting.vue')['default']
    ThemeSwitcher: typeof import('./src/components/system_setting/ThemeSwitcher.vue')['default']
    UserAgreement: typeof import('./src/components/setting/UserAgreement.vue')['default']
  }
}
