/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./components/user/Account.vue')['default']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AssistantList: typeof import('./components/ai_chat/AssistantList.vue')['default']
    ATable: typeof import('ant-design-vue/es')['Table']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    ChangePassword: typeof import('./components/user/ChangePassword.vue')['default']
    ChatAside: typeof import('./components/ai_chat/ChatAside.vue')['default']
    ChatPanel: typeof import('./components/ai_chat/ChatPanel.vue')['default']
    ConversationTest: typeof import('./components/ai_test/ConversationTest.vue')['default']
    CreateAssistantModal: typeof import('./components/ai_chat/CreateAssistantModal.vue')['default']
    EditAssistantModal: typeof import('./components/ai_chat/EditAssistantModal.vue')['default']
    EditKnowledgeModal: typeof import('./components/ai_chat/EditKnowledgeModal.vue')['default']
    Knowledge: typeof import('./components/ai_test/Knowledge.vue')['default']
    KnowledgeHome: typeof import('./components/knowledge/KnowledgeHome.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    NotFound: typeof import('./components/not_found/NotFound.vue')['default']
    PrivacyPolicy: typeof import('./components/setting/PrivacyPolicy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingInput: typeof import('./components/ai_test/SettingInput.vue')['default']
    SystemSetting: typeof import('./components/setting/SystemSetting.vue')['default']
    UserAgreement: typeof import('./components/setting/UserAgreement.vue')['default']
  }
}
